[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
evm_version = "cancun"
allow_internal_expect_revert = true
via_ir = true
ignored_error_codes = [2394]

[fuzz]
runs = 5000
max_test_rejects = 150000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
