[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
allow_internal_expect_revert = true
via_ir = true
ignored_error_codes = [2394]

[fuzz]
runs = 5000

[fmt]
line_length = 120
tab_width = 4
quote_style = "double"
func_attrs_with_params_multiline = true
inline_attribute_style = "compact"
return_statement = "inline"

[lint]
lint_on_build = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
